apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    elasticsearch.hosts: ["http://192.168.9.125:9200"]
    server.host: "0.0.0.0"
    server.shutdownTimeout: "5s"
    monitoring.ui.container.elasticsearch.enabled: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
        tier: frontend
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.16.3
        ports:
        - containerPort: 5601
        volumeMounts:
        - name: kibana-config-volume
          mountPath: /usr/share/kibana/config
          readOnly: true
      volumes:
      - name: kibana-config-volume
        configMap:
          name: kibana-config
 
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
    tier: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-internal
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
    tier: frontend
